export const onSaleProductList = [
  {
    id: 1,
    title: 'Fitness Watch',
    description: '',
    price: '40.00',
    discountPercentage: 10,
    rating: 4,
    stock: 100,
    brand: 'watches',
    thumbnail: './Assets/products/onsale-product1.png',
    images: ['', '', '', ''],
  },
  {
    id: 2,
    title: 'Sunglasses',
    description: '',
    price: '25.00',
    discountPercentage: 20,
    rating: 4.5,
    stock: 100,
    brand: 'glasses',
    thumbnail: './Assets/products/onsale-product2.png',
    images: ['', '', '', ''],
  },
  {
    id: 3,
    title: 'Leather Watch',
    description: '',
    price: '95.00',
    discountPercentage: 20,
    rating: 5,
    stock: 100,
    brand: '',
    category: 'watches',
    thumbnail: './Assets/products/onsale-product3.png',
    images: ['', '', '', ''],
  },
  {
    id: 4,
    title: 'Formal Shoes',
    description: '',
    price: '70.00',
    discountPercentage: 10,
    rating: 3.5,
    stock: 100,
    brand: '',
    category: 'shoes',
    thumbnail: './Assets/products/onsale-product4.png',
    images: ['', '', '', ''],
  },
];

export const newProductsProductList = [
  {
    id: 5,
    title: 'ViewSonic 27" Monitor',
    description: '',
    price: '165.00',
    discountPercentage: 0,
    rating: 3.5,
    stock: 200,
    brand: '',
    category: '',
    thumbnail: './Assets/new-arrivals/product-1.png',
    images: ['', '', '', ''],
  },
  {
    id: 6,
    title: 'Christmas Sweatshirt',
    description: '',
    price: '20.40',
    discountPercentage: 0,
    rating: 4,
    stock: 200,
    brand: '',
    category: '',
    thumbnail: './Assets/new-arrivals/product-2.png',
    images: ['', '', '', ''],
  },
  {
    id: 7,
    title: "Men's Belt",
    description: '',
    price: '22.98',
    discountPercentage: 0,
    rating: 4.5,
    stock: 200,
    brand: '',
    category: '',
    thumbnail: './Assets/new-arrivals/product-3.png',
    images: ['', '', '', ''],
  },
  {
    id: 8,
    title: 'LeNovo YogaBook 9i',
    description: '',
    price: '699.00',
    discountPercentage: 0,
    rating: 5,
    stock: 200,
    brand: '',
    category: '',
    thumbnail: './Assets/new-arrivals/product-4.png',
    images: ['', '', '', ''],
  },
  {
    id: 9,
    title: '4 in 1 Christmas Set',
    description: '',
    price: '108.00',
    discountPercentage: 0,
    rating: 4,
    stock: 200,
    brand: '',
    category: '',
    thumbnail: './Assets/new-arrivals/product-5.png',
    images: ['', '', '', ''],
  },
  {
    id: 10,
    title: 'PS5 Spider Man Edition',
    description: '',
    price: '450.00',
    discountPercentage: 0,
    rating: 5,
    stock: 200,
    brand: '',
    category: '',
    thumbnail: './Assets/new-arrivals/product-6.png',
    images: ['', '', '', ''],
  },
  {
    id: 11,
    title: 'Kid Trax Spider Man',
    description: '',
    price: '115.00',
    discountPercentage: 0,
    rating: 4,
    stock: 200,
    brand: '',
    category: '',
    thumbnail: './Assets/new-arrivals/product-7.png',
    images: ['', '', '', ''],
  },
  {
    id: 12,
    title: 'Workout System',
    description: '',
    price: '889.49',
    discountPercentage: 0,
    rating: 5,
    stock: 200,
    brand: '',
    category: '',
    thumbnail: './Assets/new-arrivals/product-8.png',
    images: ['', '', '', ''],
  },
];

export const similarProductList = [
  {
    id: 13,
    title: 'UltraRange Neo Shoe',
    description: '',
    price: '75.00',
    discountPercentage: 0,
    rating: 4,
    stock: 100,
    brand: 'Vans',
    category: 'shoes',
    thumbnail: './Assets/single-product/similar/product-1.png',
    images: ['', '', '', ''],
  },
  {
    id: 14,
    title: 'Skate Slip On Shoe',
    description: '',
    price: '65.00',
    discountPercentage: 0,
    rating: 4.5,
    stock: 100,
    brand: 'Vans',
    category: 'shoes',
    thumbnail: './Assets/single-product/similar/product-2.png',
    images: ['', '', '', ''],
  },
  {
    id: 15,
    title: 'Old Skool Block Blue',
    description: '',
    price: '95.00',
    discountPercentage: 0,
    rating: 5,
    stock: 100,
    brand: 'Vans',
    category: 'shoes',
    thumbnail: './Assets/single-product/similar/product-3.png',
    images: ['', '', '', ''],
  },
  {
    id: 16,
    title: 'Authentic SF Aura Fade',
    description: '',
    price: '50.00',
    discountPercentage: 0,
    rating: 3.5,
    stock: 100,
    brand: 'Vans',
    category: 'shoes',
    thumbnail: './Assets/single-product/similar/product-4.png',
    images: ['', '', '', ''],
  },
];
